bilibili_api:
    documentary: https://api.bilibili.com/pgc/season/index/result?st=3&order=2&style_id=-1&producer_id=-1&release_date=-1&season_status=-1&sort=0&page=1&season_type=3&pagesize=20&type=1
    fanju: https://api.bilibili.com/pgc/season/index/result?st=1&order=3&season_version=-1&spoken_language_type=-1&area=-1&is_finish=-1&copyright=-1&season_status=-1&season_month=-1&year=-1&style_id=-1&sort=0&page=1&season_type=1&pagesize=20&type=1
    guochuang: https://api.bilibili.com/pgc/season/index/result?st=4&order=3&season_version=-1&is_finish=-1&copyright=-1&season_status=-1&year=-1&style_id=-1&sort=0&page=1&season_type=4&pagesize=20&type=1
    inter: 20m
    inter1: 60s
    movie: https://api.bilibili.com/pgc/season/index/result?st=2&order=2&area=-1&style_id=-1&release_date=-1&season_status=-1&sort=0&page=1&season_type=2&pagesize=20&type=1
    tv: https://api.bilibili.com/pgc/season/index/result?st=5&order=2&area=-1&style_id=-1&release_date=-1&season_status=-1&sort=0&page=1&season_type=5&pagesize=20&type=1
    variety: https://api.bilibili.com/pgc/season/index/result?st=7&order=2&season_status=-1&style_id=-1&sort=0&page=1&season_type=7&pagesize=20&type=1
cookie:
    DedeUserID: "309348130"
    DedeUserID__ckMd5: d12f2b18a443b134
    SESSDATA: 645c8726%2C1736066272%2C4d480%2A71CjCnfbGkCKmiHufoDLSTd4R6cLeJ28kSx5ZnD39i_pW0mMyemfnmdwDrNYOb2aSOc60SVmtMNDFHZkVfYWx0Tm1BNUpqblVCTW8wQzVxT0Q1UmxqMGNvUWt6UnFDcnBmQVU2MG5PVDB3QU15eUJDa0czMzBPVnJybktkX0d5ZUdJcjlsWW5aNVp3IIEC
    bili_jct: a2a33c3b34d48e236ae957051e700d93
    sid: 4j5gzxf6
mysql:
    database: bilibili
    host: 192.168.231.149:3306
    password: 7zf4cTkjihTzn7cn
    username: bilibili
redis:
    host: 192.168.231.149:6379
    password: ""
